/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kozonits.betterfileexplorer;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalScrollBarUI;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author marce
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private int x = 0;
    private int y = 0;
    public int changes = 0;
    
    private int pressed_changestate = 1;
    public boolean PATH_CHANGED = false;
    public int SELECTED_PATH = -1;
    public boolean PATH_CHANGED_PARENT = false;
    public boolean PATH_CHANGED_NEXT = false;
    public boolean SHOW_SIZE_FOLDER_EVENT = false;
    
    private int size_state = 0; // 0=not_fullscreen 1=fullscreen
    
    public MainWindow() {
        initComponents();
        initDragEvent();
        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        this.setShape(new RoundRectangle2D.Double(0, 0, this.getSize().width, this.getSize().height, 20, 20));
    }
    
    private void initDragEvent() {
        jPanel2.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        jPanel2.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                if (size_state == 0) {
                    setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
                }
            }
        });
        
        //TableColumnResizer resizer = new TableColumnResizer(jTable1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label_folder_pathbar = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        button_back = new javax.swing.JButton();
        button_next = new javax.swing.JButton();
        button_new_folder = new javax.swing.JButton();
        button_new_file = new javax.swing.JButton();
        button_cmd = new javax.swing.JButton();
        folder_size = new javax.swing.JButton();
        button_close = new javax.swing.JButton();
        button_maxmin = new javax.swing.JButton();
        button_minimize = new javax.swing.JButton();
        button_select1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        button_new_file1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_new_file2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        LookAndFeel previousLF = UIManager.getLookAndFeel();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.put("TableHeader.focusCellBackground", Color.GRAY);
            UIManager.put("TableHeader.background", new Color(234, 234, 234));
            jScrollPane3 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            stateBar = new javax.swing.JPanel();
            stateText = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("BetterFileExplorer");
            setBackground(new java.awt.Color(234, 234, 234));
            setUndecorated(true);

            jPanel3.setBackground(new java.awt.Color(28, 150, 48));

            label_folder_pathbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/ordner_pathbar.png"))); // NOI18N

            path.setBackground(new java.awt.Color(28, 150, 48));
            path.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            path.setForeground(new java.awt.Color(255, 255, 255));
            path.setText("Start");
            path.setBorder(null);
            path.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pathActionPerformed(evt);
                }
            });
            path.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    pathKeyPressed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(label_folder_pathbar)
                    .addGap(18, 18, 18)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_folder_pathbar))
                    .addContainerGap())
            );

            jPanel2.setBackground(new java.awt.Color(31, 165, 55));
            jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    jPanel2MouseDragged(evt);
                }
            });
            jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel2MouseClicked(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jPanel2MousePressed(evt);
                }
            });

            button_back.setBackground(new java.awt.Color(31, 165, 55));
            button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/back_titlebar.png"))); // NOI18N
            button_back.setBorder(null);
            button_back.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_backMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_backMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_backMouseExited(evt);
                }
            });
            button_back.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    button_backActionPerformed(evt);
                }
            });

            button_next.setBackground(new java.awt.Color(31, 165, 55));
            button_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/next_titlebar.png"))); // NOI18N
            button_next.setToolTipText("");
            button_next.setBorder(null);
            button_next.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_nextMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_nextMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_nextMouseExited(evt);
                }
            });

            button_new_folder.setBackground(new java.awt.Color(31, 165, 55));
            button_new_folder.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            button_new_folder.setForeground(new java.awt.Color(255, 255, 255));
            button_new_folder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/neuer_ordner_titlebar.png"))); // NOI18N
            button_new_folder.setText("Neuer Ordner");
            button_new_folder.setToolTipText("");
            button_new_folder.setBorder(null);
            button_new_folder.setBorderPainted(false);
            button_new_folder.setIconTextGap(6);
            button_new_folder.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_new_folderMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_new_folderMouseExited(evt);
                }
            });

            button_new_file.setBackground(new java.awt.Color(31, 165, 55));
            button_new_file.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            button_new_file.setForeground(new java.awt.Color(255, 255, 255));
            button_new_file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/neue_datei_titlebar.png"))); // NOI18N
            button_new_file.setText("Neue Datei");
            button_new_file.setToolTipText("");
            button_new_file.setBorder(null);
            button_new_file.setIconTextGap(6);
            button_new_file.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_new_fileMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_new_fileMouseExited(evt);
                }
            });

            button_cmd.setBackground(new java.awt.Color(31, 165, 55));
            button_cmd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            button_cmd.setForeground(new java.awt.Color(255, 255, 255));
            button_cmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/cmd_titlebar.png"))); // NOI18N
            button_cmd.setText("CMD öffnen");
            button_cmd.setToolTipText("");
            button_cmd.setBorder(null);
            button_cmd.setIconTextGap(6);
            button_cmd.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_cmdMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_cmdMouseExited(evt);
                }
            });

            folder_size.setBackground(new java.awt.Color(31, 165, 55));
            folder_size.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            folder_size.setForeground(new java.awt.Color(255, 255, 255));
            folder_size.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/select_titlebar.png"))); // NOI18N
            folder_size.setText("Ordnergrößen");
            folder_size.setToolTipText("");
            folder_size.setBorder(null);
            folder_size.setIconTextGap(6);
            folder_size.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    folder_sizeMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    folder_sizeMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    folder_sizeMouseExited(evt);
                }
            });
            folder_size.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    folder_sizeActionPerformed(evt);
                }
            });

            button_close.setBackground(new java.awt.Color(31, 165, 55));
            button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/close.png"))); // NOI18N
            button_close.setToolTipText("");
            button_close.setBorder(null);
            button_close.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_closeMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_closeMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_closeMouseExited(evt);
                }
            });

            button_maxmin.setBackground(new java.awt.Color(31, 165, 55));
            button_maxmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/max_min.png"))); // NOI18N
            button_maxmin.setToolTipText("");
            button_maxmin.setBorder(null);
            button_maxmin.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_maxminMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_maxminMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_maxminMouseExited(evt);
                }
            });

            button_minimize.setBackground(new java.awt.Color(31, 165, 55));
            button_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/minimize.png"))); // NOI18N
            button_minimize.setToolTipText("");
            button_minimize.setBorder(null);
            button_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_minimizeMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_minimizeMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_minimizeMouseExited(evt);
                }
            });
            button_minimize.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    button_minimizeActionPerformed(evt);
                }
            });

            button_select1.setBackground(new java.awt.Color(31, 165, 55));
            button_select1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            button_select1.setForeground(new java.awt.Color(255, 255, 255));
            button_select1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/select_titlebar.png"))); // NOI18N
            button_select1.setText("Auswählen");
            button_select1.setToolTipText("");
            button_select1.setBorder(null);
            button_select1.setIconTextGap(6);
            button_select1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_select1MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_select1MouseExited(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_new_folder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_new_file, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_select1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(folder_size, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(button_maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(button_new_folder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_new_file, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addComponent(button_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_maxmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_select1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_cmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(folder_size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jPanel4.setBackground(new java.awt.Color(221, 221, 221));

            button_new_file1.setBackground(new java.awt.Color(221, 221, 221));
            button_new_file1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
            button_new_file1.setForeground(new java.awt.Color(64, 64, 64));
            button_new_file1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/start_fav.png"))); // NOI18N
            button_new_file1.setText("Mein PC");
            button_new_file1.setToolTipText("");
            button_new_file1.setBorder(null);
            button_new_file1.setIconTextGap(9);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/arrow_fav.png"))); // NOI18N

            button_new_file2.setBackground(new java.awt.Color(221, 221, 221));
            button_new_file2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
            button_new_file2.setForeground(new java.awt.Color(64, 64, 64));
            button_new_file2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/ordner_list.png"))); // NOI18N
            button_new_file2.setText("Favoriten");
            button_new_file2.setToolTipText("");
            button_new_file2.setBorder(null);
            button_new_file2.setIconTextGap(9);

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kozonits/betterfileexplorer/arrow_fav.png"))); // NOI18N

            jScrollPane2.setBorder(null);

            jList1.setBackground(new java.awt.Color(221, 221, 221));
            jList1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
            jList1.setForeground(new java.awt.Color(64, 64, 64));
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Dokumente", "Bilder", "Videos", "Desktop" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jList1.setToolTipText("");
            jList1.setFixedCellHeight(20);
            jList1.setSelectionBackground(new java.awt.Color(200, 200, 200));
            jList1.setSelectionForeground(new java.awt.Color(64, 64, 64));
            jScrollPane2.setViewportView(jList1);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_new_file1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(button_new_file2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addContainerGap(114, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1))
                        .addComponent(button_new_file1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2))
                        .addComponent(button_new_file2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(453, Short.MAX_VALUE))
            );

            jPanel5.setBackground(new java.awt.Color(240, 240, 240));

            UIManager.setLookAndFeel(previousLF);
        } catch (IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException | ClassNotFoundException e) {}
        jScrollPane3.setBackground(new java.awt.Color(234, 234, 234));
        jScrollPane3.setBorder(createEmptyBorder());
        jScrollPane3.setForeground(new java.awt.Color(32, 32, 32));
        jScrollPane3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(32, 32, 32));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Name", "Dateityp", "Größe", "Sonstiges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(180, 180, 180));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(180, 180, 180));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        jTable1.setIntercellSpacing(new Dimension());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        //setScrollBars(jScrollPane3);

        stateBar.setBackground(new java.awt.Color(220, 220, 220));

        stateText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        stateText.setForeground(new java.awt.Color(50, 50, 50));
        stateText.setText("No Files/Folder selected.");

        javax.swing.GroupLayout stateBarLayout = new javax.swing.GroupLayout(stateBar);
        stateBar.setLayout(stateBarLayout);
        stateBarLayout.setHorizontalGroup(
            stateBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stateBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stateText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stateBarLayout.setVerticalGroup(
            stateBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(stateBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(stateBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_backActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        /*this.positionx = evt.getXOnScreen();
        this.positiony = evt.getYOnScreen();
        pressed_changestate = 0;
        
        this.setLocation(this.positionx - this.x1, this.positiony - this.y1);*/
    }//GEN-LAST:event_jPanel2MouseDragged

    private void button_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_button_closeMouseClicked

    private void button_maxminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_maxminMouseClicked
        size_state++;
        if (size_state > 1)
            size_state = 0;
        
        if (size_state == 1)
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        else
            setExtendedState(JFrame.NORMAL);
    }//GEN-LAST:event_button_maxminMouseClicked

    private void button_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_minimizeMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_button_minimizeMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        /*if (pressed_changestate == 1) {
            this.x1 = this.getX();
            this.x2 = this.getY();
        } */
    }//GEN-LAST:event_jPanel2MousePressed

    private void button_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_minimizeActionPerformed

    private void button_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseEntered
        button_close.setBackground(Color.RED);
    }//GEN-LAST:event_button_closeMouseEntered

    private void button_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseExited
        button_close.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_closeMouseExited

    private void button_maxminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_maxminMouseExited
        button_maxmin.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_maxminMouseExited

    private void button_maxminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_maxminMouseEntered
        button_maxmin.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_maxminMouseEntered

    private void button_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_minimizeMouseEntered
        button_minimize.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_minimizeMouseEntered

    private void button_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_minimizeMouseExited
        button_minimize.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_minimizeMouseExited

    private void pathKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathKeyPressed
        //
    }//GEN-LAST:event_pathKeyPressed

    private void folder_sizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_folder_sizeMouseEntered
        folder_size.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_folder_sizeMouseEntered

    private void folder_sizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_folder_sizeMouseExited
        folder_size.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_folder_sizeMouseExited

    private void button_cmdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cmdMouseEntered
        button_cmd.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_cmdMouseEntered

    private void button_cmdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cmdMouseExited
        button_cmd.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_cmdMouseExited

    private void button_new_fileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_new_fileMouseEntered
        button_new_file.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_new_fileMouseEntered

    private void button_new_fileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_new_fileMouseExited
        button_new_file.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_new_fileMouseExited

    private void button_new_folderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_new_folderMouseEntered
        button_new_folder.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_new_folderMouseEntered

    private void button_new_folderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_new_folderMouseExited
        button_new_folder.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_new_folderMouseExited

    private void button_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_nextMouseEntered
        button_next.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_nextMouseEntered

    private void button_nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_nextMouseExited
        button_next.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_nextMouseExited

    private void button_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_backMouseEntered
        button_back.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_backMouseEntered

    private void button_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_backMouseExited
        button_back.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_backMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            SELECTED_PATH = jTable1.getSelectedRow();
            PATH_CHANGED = true;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void button_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_backMouseClicked
        PATH_CHANGED_PARENT = true;
    }//GEN-LAST:event_button_backMouseClicked

    private void button_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_nextMouseClicked
        PATH_CHANGED_NEXT = true;
    }//GEN-LAST:event_button_nextMouseClicked

    private void button_select1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_select1MouseExited
        button_select1.setBackground(new Color(31,165,55));
    }//GEN-LAST:event_button_select1MouseExited

    private void button_select1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_select1MouseEntered
        button_select1.setBackground(new Color(28,150,48));
    }//GEN-LAST:event_button_select1MouseEntered

    private void folder_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folder_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folder_sizeActionPerformed

    private void folder_sizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_folder_sizeMouseClicked
        SHOW_SIZE_FOLDER_EVENT = true;
    }//GEN-LAST:event_folder_sizeMouseClicked

    /*private void setScrollBars(JScrollPane pane) {
        setScrollBar(pane, JScrollBar.VERTICAL);
        setScrollBar(pane, JScrollBar.HORIZONTAL);
    }*/
    /*private void setScrollBar(JScrollPane pane, int adjustmend) {
        JScrollBar bar = new JScrollBar(adjustmend);
        bar.setUI(new MyScrollBarUI());
        if(adjustmend == JScrollBar.VERTICAL) {
            pane.setVerticalScrollBar(bar);
        } else if(adjustmend == JScrollBar.HORIZONTAL) {
            pane.setHorizontalScrollBar(bar);
        } else {
            //IllegalArgumentException
        }
    }*/

    /*public class MyScrollBarUI extends MetalScrollBarUI {
        protected void paintThumb(final Graphics g, final JComponent c, final Rectangle thumbBounds) {
                if(thumbBounds.isEmpty() || !scrollbar.isEnabled()) {
                    return;
            }

            int w = thumbBounds.width;
            int h = thumbBounds.height;

            g.translate(thumbBounds.x, thumbBounds.y);

            g.setColor(thumbDarkShadowColor);
            g.drawRect(0, 0, w-1, h-1);    
            //g.setColor(new Color(28,150,48));
            g.setColor(Color.LIGHT_GRAY);
            g.fillRect(0, 0, w-1, h-1);

            g.setColor(Color.LIGHT_GRAY);
            g.drawLine(1, 1, 1, h-2);
            g.drawLine(2, 1, w-3, 1);

            g.setColor(thumbLightShadowColor);
            g.drawLine(2, h-2, w-2, h-2);
            g.drawLine(w-2, 1, w-2, h-3);

            g.translate(0 - thumbBounds.x, 0 - thumbBounds.y);
        }
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton button_back;
    protected javax.swing.JButton button_close;
    protected javax.swing.JButton button_cmd;
    protected javax.swing.JButton button_maxmin;
    protected javax.swing.JButton button_minimize;
    protected javax.swing.JButton button_new_file;
    protected javax.swing.JButton button_new_file1;
    protected javax.swing.JButton button_new_file2;
    protected javax.swing.JButton button_new_folder;
    protected javax.swing.JButton button_next;
    protected javax.swing.JButton button_select1;
    protected javax.swing.JButton folder_size;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel label_folder_pathbar;
    public javax.swing.JTextField path;
    public javax.swing.JPanel stateBar;
    public javax.swing.JLabel stateText;
    // End of variables declaration//GEN-END:variables
}
